version: "3.7"
services:
  mariadb:
    restart: on-failure
    image: docker.io/mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PWD}
    volumes:
      - mariadb-data:/var/lib/mysql
#    ports:
#      - 3306:3306

  redis-cache:
    image: docker.io/redis:alpine

  redis-queue:
    image: docker.io/redis:alpine

  frappe:
    restart: on-failure
    image: docker.io/frappe/bench:latest
    command: /entrypoint/entrypoint.sh
    environment:
      - SHELL=/bin/bash
      - URL_SITE=api.tripwe.local
      - MARIADB_PWD=${MARIADB_PWD}
    volumes:
      - frappe:/workspace
      - ./entrypoint:/entrypoint
    working_dir: /workspace
    user: "1000:${GID}"
    expose:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
    # ports:
    #   - 8000-8005:8000-8005
    #   - 9000-9005:9000-9005

  # web:
  #   image: nginx:latest
  #   depends_on:
  #     - frappe
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - frappe:/workspace
  #   restart: on-failure
    # extra_hosts: # for linux hosts since version 20.10
    #   - host.docker.internal:host-gateway

volumes:
  mariadb-data:
  frappe:

