version: "3.7"
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1
services:
  mariadb:
    restart: on-failure
    image: docker.io/mariadb:10.6
    networks:
      default:
        ipv4_address: 172.26.0.2
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PWD}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3
#    ports:
#      - 3306:3306

  redis-cache:
    image: docker.io/redis:alpine
    networks:
      default:
        ipv4_address: 172.26.0.101

  redis-queue:
    image: docker.io/redis:alpine
    networks:
      default:
        ipv4_address: 172.26.0.100

  frappe:
    container_name: frappe
    networks:
      default:
        ipv4_address: 172.26.0.5
    restart: on-failure
    # image: docker.io/frappe/bench:latest
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    # command: /entrypoint/entrypoint.sh
    environment:
      - SHELL=/bin/bash
      - URL_SITE=tripwe.local
      - MARIADB_PWD=${MARIADB_PWD}
    volumes:
      - ./dev:/workspace
      #- frappe:/workspace
      # - ./entrypoint:/entrypoint
    working_dir: /workspace
    # user: "1000:${GID}"
    expose:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
    depends_on:
      mariadb:
        condition: service_healthy

  # web:
  #   image: nginx:latest
  #   depends_on:
  #     - frappe
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - frappe:/workspace
  #   restart: on-failure
    # extra_hosts: # for linux hosts since version 20.10
    #   - host.docker.internal:host-gateway

volumes:
  mariadb-data:
  frappe:

